server:
  port: 9999
spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      server-addr: 192.168.126.13:8848
      discovery:
        namespace: 0d70f7cc-3925-4f2a-a212-bd7053c89864
        group: DEFAULT_GROUP
  datasource:
    url: jdbc:mysql://192.168.126.13:3306/movie_recommendation?&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezon=GMT%28
    username: root
    password: Pcy90321.
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:mapperxml/*.xml